config/routes.rb
Rails.application.routes.draw do

  resources :users

  get 'sessions/create'

  resources :recipes
	get 'welcome' => 'welcome#index'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  #oauth
  get 'auth/twitter/callback', to: 'sessions#twitter', as: :twitter_auth
  get 'auth/failure', to: 'sessions#failure'

  root 'welcome#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
require 'securerandom'

class User < ActiveRecord::Base
  has_secure_password

  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.where(user_id: session[:user_id])
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe.clicks = @recipe.clicks + 1
    @recipe.save
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = session[:user_id]
    @recipe.clicks = 0

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :ingredients, :steps, :prep_time, :cook_time, :show)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper 
  
  def new
  end

  def create
    user = User.where(email: params[:email]).first

    if user && params[:password].present? && user.authenticate(params[:password])
      session[:user_id] = user.id 
      redirect_to welcome_path, notice: "You have successfully signed in.  Your username is #{user.email}."
    else
      flash[:error] = "There was a problem with your login for #{params[:email]}.  Please try again."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to welcome_path, notice: 'You have been logged out'
  end

  def twitter
    auth = request.env["omniauth.auth"]
    if current_user
      current_user.update_attribute(:uid, auth["uid"])
      flash[:notice] = 'Success!  Twitter account linked.'
      redirect_to welcome_path
    elsif 
      user = User.where(uid: auth['uid']).first || User.from_twitter(auth)
      if user
        session[:user_id] = user.id
        flash[:notice] = "Success!  You have been logged in through Twitter as #{user.name}."
        redirect_back_or root_url
      end
    end
  end

  def failure
    flash[:error] = "Oops!  Something went wrong with your authentication"
    redirect_back_or root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      UserMailer.welcome_email(@user).deliver_now
      redirect_to welcome_path, notice: "You signed up -- good for you!"
    else
      flash[:error] = @user.errors.full_messages
      render "new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @recipe = Recipe.where(show: true).order(clicks: :desc).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def signed_in?
    !current_user.nil?
  end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flasher.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div> 
      <% if msg.kind_of?(Array) %>
        <ul>
          <% for message in msg %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% else %>
        <%= msg %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<div class="large-3 columns">
  <ul class="inline-list">
    <% if signed_in? %>
      <li><%= link_to 'My Recipes', recipes_path %></li>
      <li>|</li>
      <li><%= link_to "Log Out", logout_path %></li>
    <% else %>
      <li><%= link_to "Sign Up", new_user_path %></li>
      <li>|</li>
      <li><%= link_to "Log In", login_path %></li>
    <% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Recipebook" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if flash[:notice] || flash[:error] %>
      <div class="row alert-box <%= flash[:notice] ? 'info' : 'warning' %> radius">
        <%= render 'layouts/flasher' %>
      </div>
    <% end %>
    <div class="row">
      <div class="large-9 columns">
        <h1><%= link_to "Recipebook", welcome_path %></h1>
      </div>
      <%= render 'layouts/nav' %>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div>
    <footer class="row" >
      <section class="small-7 columns">
        Copyright 2015
      </section>
      <section class="small-5 columns" >
			A Recipe Repository
      </section>
    </footer>  
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <div class="row">
      <h3> Title: </h3>
      <%= f.text_field :name, :placeholder => "Enter the title of this recipe"%>
    </div>
    <div class="row">
      Do you want other people to see this? <%= f.check_box :show %>
    </div>
  </p>
  <p>
    <div class="row">
      <div class="medium-6 columns">
        <h3> Prep time: </h3>
        <%= f.text_field :prep_time, :placeholder => "Enter how many minutes it takes to prep this recipe" %>
      </div>
      <div class="medium-6 columns">
        <h3> Cook time: </h3>
        <%= f.text_field :cook_time, :placeholder => "Enter how many minutes it takes to cook this recipe"%> 
      </div>
    </div>

    <div class="row">
      <h3>Ingredients:</h3>
      <%= f.text_area(:ingredients, size: '50x10', :placeholder => "Enter ingredients and quantity, e.g. 1 cup of sugar") %>
    </div>
    <div class="row">
      <h3>Instructions:</h3>
      <%= f.text_area(:steps, size: '50x10', :placeholder => "Enter instructions on how to create this delicious recipe") %>
    </div>
  </p>
  <p>
    <div class="row">
      <%= f.submit :class => "button small"%>
    </div>
  </p>
<% end %>

app/views/recipes/edit.html.erb
<%# Update Recipe%>

<%= render 'form' %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <table class="medium-12 columns">
    <thead>
      <tr class= "row">
        <td class="medium-12 columns text-right"> <%= link_to raw('Create Recipe <i class="fi-plus"></i>'), new_recipe_path %></td>
      </tr>
    </thead>
    <tbody>
      <% if @recipes.count < 1 %>
          <tr class="row">
            <td class="medium-12 columns text-center">You currently don't have any recipes... </td>
          </tr>
      <%else%>
        <% @recipes.each do |recipe| %>
          <tr class="row">
            <td class="medium-8 columns"><%= link_to recipe.name, recipe %> </td>
            <td class="medium-2 columns text-right"><%= link_to raw('Edit <i class="fi-pencil"></i>'), edit_recipe_path(recipe) %></td>
            <td class="medium-2 columns text-right"><%= link_to raw('Delete <i class="fi-x"></i>'), recipe,  method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <%end%>
    </tbody>
  </table>

</div>

<div class="row">
</div>

app/views/recipes/new.html.erb
<%# create Recipe%>
<%= render 'form' %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel">
  <div class="row text-center">
    <h2> 
      <strong><%= @recipe.name %></strong>
      <small><%= link_to raw('<i class="fi-pencil"></i>'), edit_recipe_path(@recipe) %></small>
    </h2>
    <br>
    <p>
    <strong>Prep Time:</strong> <%= @recipe.prep_time %> min<br>   
    <strong>Cook Time:</strong> <%= @recipe.cook_time %> min
    </p>
    <br>
    <p>
    <strong>Ingredients:</strong><br>
    <%= simple_format(@recipe.ingredients) %>
    </p>
    <br>
    <p>
    <strong>How to make it:</strong><br>
    <%= simple_format(@recipe.steps) %>
    </p>
  
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <section class="large-5 columns">
    <h4>Sign Up:</h4>
    <%= form_for @user do |f| %>
      <div> 
          <%= f.label :email %>
          <%= f.text_field :email %>
      </div>
      <div>
        <%= f.label :password  %>
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <div> 
        <%= button_tag "Submit", class: 'radius' %>   
      </div>
    <% end %>
  </section>
</div>

app/views/welcome/index.html.erb
<div class="panel">
  <p>
  <div class="row primary-color">
    <div class="large-12 text-center"> 
      Welcome to Recipebook! The world's most exclusive recipe sharing site! <br>
      Start sharing recipes today by <u><%= link_to "logging in", login_path %></u> to your account.<br>
      Happy sharing! Because sharing is Caring!!!
    </div>
  </div>
  </p>
  <%if @recipe %>
    <p> 
      <div class="row text-center">
        <h4>No 1. Recipe of the Day </h4>
        <div class="large-12 columns">
          <h5><%= @recipe.name %></h5>
          <p>
          <strong>Prep Time:</strong> <%= @recipe.prep_time %> min<br>   
          <strong>Cook Time:</strong> <%= @recipe.cook_time %> min
          </p>
          <p>
          <strong>Ingredients:</strong><br>
          <%= simple_format(@recipe.ingredients) %>
          </p>
          <p>
          <strong>How to make it:</strong><br>
          <%= simple_format(@recipe.steps) %>
          </p>

        </div> 
      </div>
    </p>
  <% end %>
</div>